extends: airbnb
parser: babel-eslint
rules:
  consistent-return: 0
  comma-dangle: 0
  curly:
    - 2
    - multi
  func-names: 2
  func-style:
    - 2
    - expression
    - allowArrowFunctions: true
  global-require: 0
  import/no-unresolved: 0
  indent:
    - 2
    - 4
    - SwitchCase: 1
  max-len:
    - 2
    - code: 100
      tabWidth: 4
  new-cap: 0
  no-implicit-coercion: 2
  no-confusing-arrow: 0
  no-console: 2
  no-underscore-dangle: 0
  padded-blocks: 0
  semi:
    - 2
    - always
  react/jsx-indent:
    - 2
    - 4
  react/jsx-indent-props:
    - 2
    - 4
  react/jsx-boolean-value: 0
  react/prefer-stateless-function: 2
  react/no-is-mounted: 2
  react/prefer-es6-class: 2
  react/jsx-curly-spacing:
    - 2
    - always
  react/jsx-handler-names: 2
  react/jsx-key: 2
  react/jsx-no-bind: 2
  react/jsx-no-duplicate-props: 2
  react/jsx-pascal-case: 2
  mocha/no-exclusive-tests: 2
plugins:
  - react
  - mocha
env:
  mocha: true
  browser: true
  node: true
