export const FETCH_POSTS_STARTED = 'FETCH_POSTS_STARTED'
export const FETCH_POSTS_COMPLETED = 'FETCH_POSTS_COMPLETED'
export const FETCH_POSTS_ERROR = 'FETCH_POSTS__ERROR'

export const SAVE_POST_STARTED = 'SAVE_POST_STARTED'
export const SAVE_POST_COMPLETED = 'SAVE_POST_COMPLETED'
export const SAVE_POST_ERROR = 'SAVE_POST_ERROR'

export const EDIT_POST_STARTED = 'EDIT_POST_STARTED'

export const UPDATE_POST_STARTED = 'UPDATE_POST_STARTED'
export const UPDATE_POST_COMPLETED = 'UPDATE_POST_COMPLETED'
export const UPDATE_POST_ERROR = 'UPDATE_POST_ERROR'

export const DELETE_POST_STARTED = 'DELETE_POST_STARTED'
export const DELETE_POST_COMPLETED = 'DELETE_POST_COMPLETED'
export const DELETE_POST_ERROR = 'DELETE_POST_ERROR'

export const FETCH_CATEGORIES_STARTED = 'FETCH_CATEGORIES_STARTED'
export const FETCH_CATEGORIES_COMPLETED = 'FETCH_CATEGORIES_COMPLETED'
export const FETCH_CATEGORIES_ERROR = 'FETCH_CATEGORIES_ERROR'

export const OPEN_MODAL = 'OPEN_MODAL'
export const HIDE_MODAL = 'HIDE_MODAL'

export const HIDE_ALERT = 'HIDE_ALERT'
